server:
  port: 7071
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
  cloud:
    consul:
      host: 192.168.2.104
      port: 8500
      discovery:
        heartbeat:
          enabled: true
        instance-id: provider-backups:${server.port}
        service-name: ${spring.application.name}
  application:
    name: consul-provider
